stages:
  - test-project
  - test
  - build
  - dist

image: greyrook/cde-dev-py3:7c2968a015888e51ec3a5c1b5e14802e31f93eaf

docs:
  stage: build
  script:
    - poetry install
    - poetry run mkdocs build
  artifacts:
    name: docs
    # only available in newer gitlab versions
    expose_as: docs
    paths:
      - site/


pages:
  stage: dist
  script:
    - mkdir public
    - mv site/* public/
  artifacts:
    paths:
    - public
  only:
    - master